// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs2-GQArmWmSd2cLCGg4MBqdT_-kq1Gik',
    appId: '1:677410887395:web:307055112a6efe4c7317d6',
    messagingSenderId: '677410887395',
    projectId: 'quickbite-fc981',
    authDomain: 'quickbite-fc981.firebaseapp.com',
    storageBucket: 'quickbite-fc981.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeCJNRDBxNBMzH6zTv30RpWPXfnwc-0Aw',
    appId: '1:677410887395:ios:04a98951dd13025c7317d6',
    messagingSenderId: '677410887395',
    projectId: 'quickbite-fc981',
    storageBucket: 'quickbite-fc981.firebasestorage.app',
    iosBundleId: 'com.example.quickbite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeCJNRDBxNBMzH6zTv30RpWPXfnwc-0Aw',
    appId: '1:677410887395:ios:04a98951dd13025c7317d6',
    messagingSenderId: '677410887395',
    projectId: 'quickbite-fc981',
    storageBucket: 'quickbite-fc981.firebasestorage.app',
    iosBundleId: 'com.example.quickbite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs2-GQArmWmSd2cLCGg4MBqdT_-kq1Gik',
    appId: '1:677410887395:web:7de6d690b0f671be7317d6',
    messagingSenderId: '677410887395',
    projectId: 'quickbite-fc981',
    authDomain: 'quickbite-fc981.firebaseapp.com',
    storageBucket: 'quickbite-fc981.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWZOXbFUC71opZyuj3KPCwJeCuNvYrUI0',
    appId: '1:677410887395:android:18bc06b9999b2cb67317d6',
    messagingSenderId: '677410887395',
    projectId: 'quickbite-fc981',
    storageBucket: 'quickbite-fc981.firebasestorage.app',
  );

}